import { tokens } from "../theme";


export const mockDataSE = [
  {
    id: 1,
    name: "Green Earth Initiative",
    mentor: "Dr. Jane Goodall",
    sdg: "SDG 13 - Climate Action",
    contact: "(665)121-5454",
    members: 15,
    program: "Environmental Awareness",
    status: "Active",
  },
  {
    id: 2,
    name: "Women Rising",
    mentor: "Malala Yousafzai",
    sdg: "SDG 5 - Gender Equality",
    contact: "(421)314-2288",
    members: 20,
    program: "Women Empowerment",
    status: "Active",
  },
  {
    id: 3,
    name: "Sustainable Futures",
    mentor: "Elon Musk",
    sdg: "SDG 12 - Responsible Consumption and Production",
    contact: "(422)982-6739",
    members: 10,
    program: "Sustainable Production",
    status: "Active",
  },
  {
    id: 4,
    name: "Education for All",
    mentor: "Kofi Annan",
    sdg: "SDG 4 - Quality Education",
    contact: "(921)425-6742",
    members: 25,
    program: "Educational Outreach",
    status: "Active",
  },
  {
    id: 5,
    name: "Clean Energy Now",
    mentor: "Bill Gates",
    sdg: "SDG 7 - Affordable and Clean Energy",
    contact: "(421)445-1189",
    members: 12,
    program: "Renewable Energy Advocacy",
    status: "Active",
  },
  {
    id: 6,
    name: "Equal Opportunity Initiative",
    mentor: "Michelle Obama",
    sdg: "SDG 10 - Reduced Inequality",
    contact: "(232)545-6483",
    members: 18,
    program: "Social Inclusion Programs",
    status: "Inactive",
  },
  {
    id: 7,
    name: "Fair Work Alliance",
    mentor: "Richard Branson",
    sdg: "SDG 8 - Decent Work and Economic Growth",
    contact: "(543)124-0123",
    members: 22,
    program: "Economic Development",
    status: "Active",
  },
  {
    id: 8,
    name: "Zero Hunger Initiative",
    mentor: "José Andrés",
    sdg: "SDG 2 - Zero Hunger",
    contact: "(222)444-5555",
    members: 30,
    program: "Food Security Initiative",
    status: "Active",
  },
  {
    id: 9,
    name: "Justice League",
    mentor: "Ruth Bader Ginsburg",
    sdg: "SDG 16 - Peace, Justice, and Strong Institutions",
    contact: "(444)555-6239",
    members: 14,
    program: "Rule of Law Advocacy",
    status: "Inactive",
  },
];


export const mockDataEval = [
  {
    id: 1,
    evaluationDate: "2024-01-15",
    mentorName: "John Doe",
    seName: "Eco Innovations",
  },
  {
    id: 2,
    evaluationDate: "2024-02-10",
    mentorName: "Jane Smith",
    seName: "Tech Solutions",
  },
  {
    id: 3,
    evaluationDate: "2024-03-05",
    mentorName: "Alice Johnson",
    seName: "Green Earth",
  },
  {
    id: 4,
    evaluationDate: "2024-04-20",
    mentorName: "Michael Lee",
    seName: "Future Builders",
  },
  {
    id: 5,
    evaluationDate: "2024-05-15",
    mentorName: "Emily Brown",
    seName: "Community Impact",
  },
];

export const mockDataSEDB = [
  {
    id: 1,
    socialEnterprise: "Green Earth",
    mentor: "Jon Snow",
  },
  {
    id: 2,
    socialEnterprise: "Eco Warriors",
    mentor: "Cersei Lannister",
  },
  {
    id: 3,
    socialEnterprise: "Solar Innovators",
    mentor: "Jaime Lannister",
  },
  {
    id: 4,
    socialEnterprise: "Clean Oceans",
    mentor: "Anya Stark",
  },
  {
    id: 5,
    socialEnterprise: "Sustainable Futures",
    mentor: "Daenerys Targaryen",
  },
  {
    id: 6,
    socialEnterprise: "Water Guardians",
    mentor: "Ever Melisandre",
  },
  {
    id: 7,
    socialEnterprise: "Tree Planters",
    mentor: "Ferrara Clifford",
  },
  {
    id: 8,
    socialEnterprise: "Green Builders",
    mentor: "Rossini Frances",
  },
  {
    id: 9,
    socialEnterprise: "Renewable Solutions",
    mentor: "Harvey Roxie",
  },
  {
    id: 10,
    socialEnterprise: "Eco Mechanics",
    mentor: "Enteri Redack",
  },
  {
    id: 11,
    socialEnterprise: "Sustainable Energy Hub",
    mentor: "Steve Goodman",
  },
];


export const mockDataInvoices = [
  {
    id: 1,
    name: "Jon Snow",
    email: "jonsnow@gmail.com",
    cost: "21.24",
    phone: "(665)121-5454",
    date: "03/12/2022",
  },
  {
    id: 2,
    name: "Cersei Lannister",
    email: "cerseilannister@gmail.com",
    cost: "1.24",
    phone: "(421)314-2288",
    date: "06/15/2021",
  },
  {
    id: 3,
    name: "Jaime Lannister",
    email: "jaimelannister@gmail.com",
    cost: "11.24",
    phone: "(422)982-6739",
    date: "05/02/2022",
  },
  {
    id: 4,
    name: "Anya Stark",
    email: "anyastark@gmail.com",
    cost: "80.55",
    phone: "(921)425-6742",
    date: "03/21/2022",
  },
  {
    id: 5,
    name: "Daenerys Targaryen",
    email: "daenerystargaryen@gmail.com",
    cost: "1.24",
    phone: "(421)445-1189",
    date: "01/12/2021",
  },
  {
    id: 6,
    name: "Ever Melisandre",
    email: "evermelisandre@gmail.com",
    cost: "63.12",
    phone: "(232)545-6483",
    date: "11/02/2022",
  },
  {
    id: 7,
    name: "Ferrara Clifford",
    email: "ferraraclifford@gmail.com",
    cost: "52.42",
    phone: "(543)124-0123",
    date: "02/11/2022",
  },
  {
    id: 8,
    name: "Rossini Frances",
    email: "rossinifrances@gmail.com",
    cost: "21.24",
    phone: "(222)444-5555",
    date: "05/02/2021",
  },
];

export const mockTransactions = [
  {
    txId: "01e4dsa",
    user: "johndoe",
    date: "2021-09-01",
    cost: "43.95",
  },
  {
    txId: "0315dsaa",
    user: "jackdower",
    date: "2022-04-01",
    cost: "133.45",
  },
  {
    txId: "01e4dsa",
    user: "aberdohnny",
    date: "2021-09-01",
    cost: "43.95",
  },
  {
    txId: "51034szv",
    user: "goodmanave",
    date: "2022-11-05",
    cost: "200.95",
  },
  {
    txId: "0a123sb",
    user: "stevebower",
    date: "2022-11-02",
    cost: "13.55",
  },
  {
    txId: "01e4dsa",
    user: "aberdohnny",
    date: "2021-09-01",
    cost: "43.95",
  },
  {
    txId: "120s51a",
    user: "wootzifer",
    date: "2019-04-15",
    cost: "24.20",
  },
  {
    txId: "0315dsaa",
    user: "jackdower",
    date: "2022-04-01",
    cost: "133.45",
  },
];

export const mockBarData = [
  {
    country: "AD",
    "hot dog": 137,
    "hot dogColor": "hsl(229, 70%, 50%)",
    burger: 96,
    burgerColor: "hsl(296, 70%, 50%)",
    kebab: 72,
    kebabColor: "hsl(97, 70%, 50%)",
    donut: 140,
    donutColor: "hsl(340, 70%, 50%)",
  },
  {
    country: "AE",
    "hot dog": 55,
    "hot dogColor": "hsl(307, 70%, 50%)",
    burger: 28,
    burgerColor: "hsl(111, 70%, 50%)",
    kebab: 58,
    kebabColor: "hsl(273, 70%, 50%)",
    donut: 29,
    donutColor: "hsl(275, 70%, 50%)",
  },
  {
    country: "AF",
    "hot dog": 109,
    "hot dogColor": "hsl(72, 70%, 50%)",
    burger: 23,
    burgerColor: "hsl(96, 70%, 50%)",
    kebab: 34,
    kebabColor: "hsl(106, 70%, 50%)",
    donut: 152,
    donutColor: "hsl(256, 70%, 50%)",
  },
  {
    country: "AG",
    "hot dog": 133,
    "hot dogColor": "hsl(257, 70%, 50%)",
    burger: 52,
    burgerColor: "hsl(326, 70%, 50%)",
    kebab: 43,
    kebabColor: "hsl(110, 70%, 50%)",
    donut: 83,
    donutColor: "hsl(9, 70%, 50%)",
  },
  {
    country: "AI",
    "hot dog": 81,
    "hot dogColor": "hsl(190, 70%, 50%)",
    burger: 80,
    burgerColor: "hsl(325, 70%, 50%)",
    kebab: 112,
    kebabColor: "hsl(54, 70%, 50%)",
    donut: 35,
    donutColor: "hsl(285, 70%, 50%)",
  },
  {
    country: "AL",
    "hot dog": 66,
    "hot dogColor": "hsl(208, 70%, 50%)",
    burger: 111,
    burgerColor: "hsl(334, 70%, 50%)",
    kebab: 167,
    kebabColor: "hsl(182, 70%, 50%)",
    donut: 18,
    donutColor: "hsl(76, 70%, 50%)",
  },
  {
    country: "AM",
    "hot dog": 80,
    "hot dogColor": "hsl(87, 70%, 50%)",
    burger: 47,
    burgerColor: "hsl(141, 70%, 50%)",
    kebab: 158,
    kebabColor: "hsl(224, 70%, 50%)",
    donut: 49,
    donutColor: "hsl(274, 70%, 50%)",
  },
];

export const mockPieData = [
  {
    id: "hack",
    label: "hack",
    value: 239,
    color: "hsl(104, 70%, 50%)",
  },
  {
    id: "make",
    label: "make",
    value: 170,
    color: "hsl(162, 70%, 50%)",
  },
  {
    id: "go",
    label: "go",
    value: 322,
    color: "hsl(291, 70%, 50%)",
  },
  {
    id: "lisp",
    label: "lisp",
    value: 503,
    color: "hsl(229, 70%, 50%)",
  },
  {
    id: "scala",
    label: "scala",
    value: 584,
    color: "hsl(344, 70%, 50%)",
  },
];



export const mockRadarData = [
  {
    category: "Challenge A",
    "Social Enterprise A": 80,
    "Social Enterprise B": 60,
    "Social Enterprise C": 70,
  },
  {
    category: "Challenge B",
    "Social Enterprise A": 40,
    "Social Enterprise B": 90,
    "Social Enterprise C": 50,
  },
  {
    category: "Challenge C",
    "Social Enterprise A": 70,
    "Social Enterprise B": 50,
    "Social Enterprise C": 60,
  },
  {
    category: "Performance A",
    "Social Enterprise A": 90,
    "Social Enterprise B": 80,
    "Social Enterprise C": 85,
  },
  {
    category: "Performance B",
    "Social Enterprise A": 60,
    "Social Enterprise B": 75,
    "Social Enterprise C": 70,
  },
];

export const mockLikertData = [
  {
    question: "Q1: How satisfied are you with the program?",
    "Strongly Disagree": 10,
    Disagree: 20,
    Neutral: 30,
    Agree: 25,
    "Strongly Agree": 15,
  },
  {
    question: "Q2: How effective is the mentorship?",
    "Strongly Disagree": 5,
    Disagree: 15,
    Neutral: 40,
    Agree: 30,
    "Strongly Agree": 10,
  },
  {
    question: "Q3: How likely are you to recommend this program?",
    "Strongly Disagree": 2,
    Disagree: 10,
    Neutral: 25,
    Agree: 40,
    "Strongly Agree": 23,
  },
  {
    question: "Q4: How clear are the program goals?",
    "Strongly Disagree": 8,
    Disagree: 12,
    Neutral: 35,
    Agree: 30,
    "Strongly Agree": 15,
  },
];

export const mockDataMentor = [
  {
    id: 1,
    mentorName: "John Doe",
    email: "john.doe@example.com",
    number: "123-456-7890",
    numberOfSEsAssigned: 5,
    status: "Active",
  },
  {
    id: 2,
    mentorName: "Jane Smith",
    email: "jane.smith@example.com",
    number: "987-654-3210",
    numberOfSEsAssigned: 3,
    status: "Inactive",
  },
  {
    id: 3,
    mentorName: "Michael Brown",
    email: "michael.brown@example.com",
    number: "555-123-4567",
    numberOfSEsAssigned: 8,
    status: "Active",
  },
  {
    id: 4,
    mentorName: "Emily Davis",
    email: "emily.davis@example.com",
    number: "444-678-9012",
    numberOfSEsAssigned: 2,
    status: "Inactive",
  },
  {
    id: 5,
    mentorName: "Chris Wilson",
    email: "chris.wilson@example.com",
    number: "789-456-1230",
    numberOfSEsAssigned: 10,
    status: "Active",
  },
  {
    id: 6,
    mentorName: "Patricia Lee",
    email: "patricia.lee@example.com",
    number: "321-654-9870",
    numberOfSEsAssigned: 6,
    status: "Active",
  },
  {
    id: 7,
    mentorName: "David Johnson",
    email: "david.johnson@example.com",
    number: "456-789-0123",
    numberOfSEsAssigned: 1,
    status: "Inactive",
  },
  {
    id: 8,
    mentorName: "Sophia Martinez",
    email: "sophia.martinez@example.com",
    number: "654-321-0987",
    numberOfSEsAssigned: 4,
    status: "Active",
  },
  {
    id: 9,
    mentorName: "James Anderson",
    email: "james.anderson@example.com",
    number: "777-888-9999",
    numberOfSEsAssigned: 7,
    status: "Inactive",
  },
  {
    id: 10,
    mentorName: "Olivia Taylor",
    email: "olivia.taylor@example.com",
    number: "111-222-3333",
    numberOfSEsAssigned: 9,
    status: "Active",
  },
  {
    id: 11,
    mentorName: "Ethan Moore",
    email: "ethan.moore@example.com",
    number: "888-999-7777",
    numberOfSEsAssigned: 0,
    status: "Inactive",
  },
  {
    id: 12,
    mentorName: "Isabella Thompson",
    email: "isabella.thompson@example.com",
    number: "222-333-4444",
    numberOfSEsAssigned: 3,
    status: "Active",
  },
  {
    id: 13,
    mentorName: "Alexander White",
    email: "alexander.white@example.com",
    number: "333-444-5555",
    numberOfSEsAssigned: 5,
    status: "Inactive",
  },
  {
    id: 14,
    mentorName: "Charlotte Harris",
    email: "charlotte.harris@example.com",
    number: "444-555-6666",
    numberOfSEsAssigned: 6,
    status: "Active",
  },
  {
    id: 15,
    mentorName: "Liam Lewis",
    email: "liam.lewis@example.com",
    number: "555-666-7777",
    numberOfSEsAssigned: 2,
    status: "Inactive",
  },
];

export const mockDataTasks = [
  {
    id: 1,
    task: "Complete Monthly Report",
    dateToAccomplish: "2025-01-30",
  },
  {
    id: 2,
    task: "Team Meeting for Project X",
    dateToAccomplish: "2025-02-05",
  },
  {
    id: 3,
    task: "Finalize Budget Proposal",
    dateToAccomplish: "2025-01-28",
  },
  {
    id: 4,
    task: "Client Presentation Prep",
    dateToAccomplish: "2025-02-03",
  },
  {
    id: 5,
    task: "Conduct Performance Reviews",
    dateToAccomplish: "2025-02-10",
  },
  {
    id: 6,
    task: "Update Marketing Strategy",
    dateToAccomplish: "2025-01-25",
  },
  {
    id: 7,
    task: "Organize Team Building Event",
    dateToAccomplish: "2025-02-15",
  },
  {
    id: 8,
    task: "Client Feedback Analysis",
    dateToAccomplish: "2025-01-27",
  },
  {
    id: 9,
    task: "Product Launch Plan",
    dateToAccomplish: "2025-02-20",
  },
];
